[package]
name = "awsdump"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.4"
aws-sdk-s3 = "1.41.0"
aws-types = "1.3.3"
bytes = "1.6.1"
tokio = { version = "1", features = ["full"] }
tokio-macros = "2.2.0"
